name: disp-s1-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - click>=7.0
  - cmap
  - gdal>=3.8  # For Footprint
  - libgdal-netcdf
  - libgdal-hdf5
  - h5netcdf>=1.0
  - matplotlib-base
  - pydantic>=2.1
  - ruamel.yaml>=0.15
  - yamale
  # Corrections
  - pysolid  # For solid earth tide corrections
  # - pyaps3
  # - xarray
  # Unwrappers:
  - snaphu>=0.4.1
  - isce3-cpu>=0.16.0 # For baseline
  - tophu
  # - cxx-compiler # for whirlwind
  - dolphin>=0.35.0
  - pip
    - spurt=0.1.0
